// test/github.test.js — Isolated testing of GitHub integration
import 'dotenv/config';
import { postTranslation, getRepoVisibility } from '../src/github.js';

async function runTest() {
  const repo = process.env.GITHUB_REPO; // e.g., "myorg/myrepo"
  const issueNumber = process.env.TEST_ISSUE_NUMBER; // e.g., "1"

  if (!repo || !issueNumber) {
    console.error('❌ Missing GITHUB_REPO or TEST_ISSUE_NUMBER in .env');
    console.log('To run this test, add these to your .env:');
    console.log('GITHUB_REPO=your-username/your-repo');
    console.log('TEST_ISSUE_NUMBER=123');
    return;
  }

  console.log(`--- Starting GitHub Integration Test for ${repo} #${issueNumber} ---\n`);

  try {
    // 1. Verify visibility
    console.log('[Step 1] Checking repository visibility...');
    const visibility = await getRepoVisibility(repo);
    console.log(`✓ Repository is ${visibility.isPrivate ? 'PRIVATE' : 'PUBLIC'}`);

    // 2. Post mock translation
    console.log('[Step 2] Posting mock translation comment...');
    const mockData = {
      locale: 'zh',
      translatedTitle: 'Mock Translated Title',
      translatedBody: 'This is a mock translation generated by the test script to verify GitHub API connectivity.',
      labels: ['bug', 'test'],
      confidence: 99
    };

    const comment = await postTranslation({ full_name: repo }, parseInt(issueNumber), mockData);
    console.log(`✓ Comment posted successfully! URL: ${comment.html_url}`);
    console.log('\n✅ GitHub Integration Test Passed!');

  } catch (err) {
    console.error('❌ GitHub Integration Test Failed:', err.message);
    if (err.status === 401) {
      console.log('TIP: Check if your GITHUB_TOKEN is valid and has "Issues" write permissions.');
    } else if (err.status === 404) {
      console.log('TIP: Ensure the repository and issue number actually exist.');
    }
  }
}

runTest();
